name: Greetings

on: [pull_request]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - name: "Greeter"
      uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        greeting: "Hey **#** welcome to this repo"
        pr-message: 'Thank you for contributing to C-HSC-Boards-2021!'
